var meme_data = {
    "1January": [],
    "2January": [],
    "3January": [],
    "4January": [],
    "5January": [],
    "6January": [],
    "7January": [],
    "8January": [],
    "9January": [],
    "10January": [],
    "11January": [],
    "12January": [],
    "13January": [],
    "14January": [],
    "15January": [],
    "16January": [],
    "17January": [],
    "18January": [],
    "19January": [],
    "20January": [],
    "21January": [],
    "22January": [],
    "23January": [],
    "24January": [],
    "25January": [],
    "26January": [],
    "27January": [],
    "28January": [],
    "29January": [],
    "30January": [],
    "31January": [],
    "1February": [],
    "2February": [],
    "3February": [],
    "4February": [],
    "5February": [],
    "6February": [],
    "7February": [],
    "8February": [],
    "9February": [],
    "10February": [],
    "11February": [],
    "12February": [],
    "13February": [],
    "14February": [],
    "15February": [],
    "16February": [],
    "17February": [],
    "18February": [],
    "19February": [],
    "20February": [
        {
            "title": "Futurama S2E6 first airs",
            "year": 2000,
            "youtube": false,
            "image": "https://i.kym-cdn.com/entries/icons/original/000/006/026/NOTSUREIF.jpg",
            "info": "On this day, the Futurama episode \"The Lesser of Two Evils\" aired for the first time. About a decade later, this still image from the episode would become the basis of a widespread meme format.",
            "kym": "https://knowyourmeme.com/memes/futurama-fry-not-sure-if"
        }
    ],
    "21February": [],
    "22February": [],
    "23February": [],
    "24February": [],
    "25February": [],
    "26February": [],
    "27February": [],
    "28February": [],
    "29February": [],
    "1March": [],
    "2March": [],
    "3March": [],
    "4March": [],
    "5March": [],
    "6March": [],
    "7March": [],
    "8March": [],
    "9March": [],
    "10March": [],
    "11March": [],
    "12March": [],
    "13March": [],
    "14March": [],
    "15March": [],
    "16March": [],
    "17March": [],
    "18March": [],
    "19March": [],
    "20March": [],
    "21March": [],
    "22March": [],
    "23March": [],
    "24March": [],
    "25March": [],
    "26March": [],
    "27March": [],
    "28March": [
        {
            "title": "\"THEN WHO WAS PHONE?\" creepypasta posted",
            "year": 2008,
            "youtube": false,
            "image": "https://i.kym-cdn.com/photos/images/newsfeed/000/109/415/tumblr_lg46betBTg1qzptwgo1_500.jpg",
            "info": "On this day, an anonymous 4chan user posted this mock-creepypasta on /x/, the paranormal board. The closing sentence, \"THEN WHO WAS PHONE?\", became a catchphrase of sorts, and spread to other websites including Yahoo Answers.",
            "kym": "https://knowyourmeme.com/memes/then-who-was-phone"
        }
    ],
    "29March": [],
    "30March": [],
    "31March": [
        {
            "title": "Sanic Hegehog created",
            "year": 2011,
            "youtube": "Eo_gJwXxshQ",
            "image": false,
            "info": "!!! Warning: the above video contains very loud music !!!\n\nOn this day, YouTube user 0nyxheart uploaded this video of themself drawing Sonic the Hedgehog in MS Paint, with a distorted version of \"Green Hill Zone\" played overtop. This image and music both became iconic - the drawing was even referenced in 2017 game Sonic Forces, and the 2020 Sonic the Hedgehog movie. The original video was eventually taken down, although mirrors (such as the one above) still exist.",
            "kym": "https://knowyourmeme.com/memes/sanic-hegehog"
        }
    ],
    "1April": [],
    "2April": [
        {
            "title": "Pop-Tart Cat GIF uploaded",
            "year": 2011,
            "youtube": false,
            "image": "https://i.kym-cdn.com/photos/images/newsfeed/000/114/779/0002.gif",
            "info": "On this day, illustrator Chris Torres (a.k.a. prguitarman) uploaded this GIF to LOL-COMICS and Tumblr. A few days later, YouTube user saraj00n would add music to this to create Nyan Cat as we know it today.",
            "kym": "https://knowyourmeme.com/memes/nyan-cat"
        }
    ],
    "3April": [],
    "4April": [
        {
            "title": "Tardar Sauce (Grumpy Cat) born",
            "year": 2012,
            "youtube": false,
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Grumpy_Cat_%2814556024763%29_%28cropped%29.jpg/800px-Grumpy_Cat_%2814556024763%29_%28cropped%29.jpg",
            "info": "On this day, the snowshoe cat Tardar Sauce was born. Later that year, owner Tabatha Bundesen's brother Bryan would post pictures of Tardar Sauce on Reddit, leading to the Grumpy Cat meme.",
            "kym": "https://knowyourmeme.com/memes/grumpy-cat"
        }
    ],
    "5April": [
        {
            "title": "Nyan Cat uploaded to YouTube",
            "year": 2011,
            "youtube": "QH2-TGUlwu4",
            "image": false,
            "info": "On this day, YouTube user saraj00n combined Chris Torres' \"Pop-Tart Cat\" GIF, which had been first uploaded just a few days prior, with the Utauloid Momo Momone's cover of the song \"Nyanyanyanyanyanyanya\".",
            "kym": "https://knowyourmeme.com/memes/nyan-cat"
        }
    ],
    "6April": [],
    "7April": [],
    "8April": [],
    "9April": [],
    "10April": [],
    "11April": [],
    "12April": [],
    "13April": [],
    "14April": [],
    "15April": [],
    "16April": [],
    "17April": [],
    "18April": [],
    "19April": [],
    "20April": [],
    "21April": [],
    "22April": [],
    "23April": [],
    "24April": [],
    "25April": [],
    "26April": [],
    "27April": [],
    "28April": [],
    "29April": [],
    "30April": [],
    "1May": [],
    "2May": [],
    "3May": [],
    "4May": [],
    "5May": [],
    "6May": [],
    "7May": [],
    "8May": [],
    "9May": [],
    "10May": [],
    "11May": [
        {
            "title": "\"Leeroy Jenkins\" video posted",
            "year": 2005,
            "youtube": "sAooq7e0gg0",
            "image": false,
            "info": "On this day, the World of Warcraft guild \"PalsForLife\" uploaded this video to Warcraft Movies. It was shared widely, and was uploaded to YouTube about six months later. From there, it became recognisable even outside the world of gaming, even being referenced on Jeopardy later that year.",
            "kym": "https://knowyourmeme.com/memes/leeroy-jenkins"
        }
    ],
    "12May": [],
    "13May": [],
    "14May": [],
    "15May": [],
    "16May": [],
    "17May": [],
    "18May": [],
    "19May": [],
    "20May": [],
    "21May": [],
    "22May": [],
    "23May": [],
    "24May": [],
    "25May": [],
    "26May": [],
    "27May": [],
    "28May": [
        {
            "title": "Harambe killed",
            "year": 2016,
            "youtube": false,
            "image": "https://i.kym-cdn.com/photos/images/newsfeed/001/200/734/6d5.jpg",
            "info": "On this day, Harambe the Western lowland gorilla was shot and killed after a 4-year-old child crawled into the gorilla enclosure at Cincinnati Zoo. This spawned a \"Justice for Harambe\" petition, as well as many memes - unfortunately, a portion of these memes were racist in nature.",
            "kym": "https://knowyourmeme.com/memes/harambe-the-gorilla"
        }
    ],
    "29May": [],
    "30May": [],
    "31May": [],
    "1June": [],
    "2June": [],
    "3June": [],
    "4June": [],
    "5June": [],
    "6June": [],
    "7June": [],
    "8June": [],
    "9June": [],
    "10June": [],
    "11June": [],
    "12June": [],
    "13June": [],
    "14June": [],
    "15June": [],
    "16June": [],
    "17June": [],
    "18June": [],
    "19June": [],
    "20June": [],
    "21June": [],
    "22June": [],
    "23June": [],
    "24June": [],
    "25June": [],
    "26June": [],
    "27June": [],
    "28June": [],
    "29June": [],
    "30June": [],
    "1July": [],
    "2July": [],
    "3July": [],
    "4July": [],
    "5July": [],
    "6July": [],
    "7July": [],
    "8July": [],
    "9July": [],
    "10July": [],
    "11July": [],
    "12July": [],
    "13July": [],
    "14July": [],
    "15July": [],
    "16July": [],
    "17July": [],
    "18July": [],
    "19July": [],
    "20July": [],
    "21July": [],
    "22July": [],
    "23July": [],
    "24July": [],
    "25July": [],
    "26July": [],
    "27July": [],
    "28July": [],
    "29July": [],
    "30July": [],
    "31July": [],
    "1August": [],
    "2August": [],
    "3August": [],
    "4August": [],
    "5August": [],
    "6August": [],
    "7August": [],
    "8August": [],
    "9August": [],
    "10August": [],
    "11August": [],
    "12August": [],
    "13August": [],
    "14August": [],
    "15August": [],
    "16August": [],
    "17August": [],
    "18August": [],
    "19August": [],
    "20August": [],
    "21August": [],
    "22August": [],
    "23August": [],
    "24August": [],
    "25August": [],
    "26August": [
        {
            "title": "\"Success Kid\" photo taken",
            "year": 2007,
            "youtube": false,
            "image": "https://i.kym-cdn.com/photos/images/newsfeed/000/185/885/SANDCASTLES.png",
            "info": "On this day, photographer Laney Griner took this photograph of her child Sammy. Initially, it was typically captioned with \"I Hate Sandcastles\", but later became the basis of the Success Kid meme. This was a hugely popular meme format, making the photo one of the most recognisable on the internet. In 2015, the family used the photo to help raise awareness of a fundraiser for a kidney transplant for Sammy's father, Justin - they reached their $75,000 goal within a few days, and the surgery was successful.",
            "kym": "https://knowyourmeme.com/memes/success-kid-i-hate-sandcastles"
        }
    ],
    "27August": [],
    "28August": [],
    "29August": [],
    "30August": [],
    "31August": [],
    "1September": [],
    "2September": [],
    "3September": [],
    "4September": [],
    "5September": [],
    "6September": [],
    "7September": [],
    "8September": [],
    "9September": [],
    "10September": [],
    "11September": [],
    "12September": [],
    "13September": [],
    "14September": [],
    "15September": [
        {
            "title": "Undertale released",
            "year": 2015,
            "youtube": false,
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Undertale_vector_logo_on_black_borders.svg/1920px-Undertale_vector_logo_on_black_borders.svg.png",
            "info": "On this day, Toby Fox released Undertale. It was hugely well received by fans, many of whom had supported the game on Kickstarter 2 years earlier. Many different memes originate from Undertale and the fan culture surrounding it, including the Annoying Dog, Megalovania, \"You're gonna have a bad time\", Temmie covers, and Papyrus' spaghetti.",
            "kym": "https://knowyourmeme.com/memes/subcultures/undertale"
        }
    ],
    "16September": [],
    "17September": [],
    "18September": [],
    "19September": [],
    "20September": [],
    "21September": [],
    "22September": [],
    "23September": [
        {
            "title": "Photos of Tardar Sauce (Grumpy Cat) first posted to Reddit",
            "year": 2012,
            "youtube": false,
            "image": "https://i.kym-cdn.com/photos/images/newsfeed/000/406/325/b31.jpg",
            "info": "On this day, Bryan Bundesen first posted pictures of his sister Tabatha's cat, Tardar Sauce, on Reddit's /r/pics subreddit. Almost instantly, huge quantities of memes and photoshops of these images were created, and the format rapidly rose in popularity. This led to Tardar Sauce (now widely known as Grumpy Cat) becoming one of the most recognisable cats in the world.",
            "kym": "https://knowyourmeme.com/memes/grumpy-cat"
        }
    ],
    "24September": [],
    "25September": [],
    "26September": [],
    "27September": [],
    "28September": [],
    "29September": [],
    "30September": [],
    "1October": [],
    "2October": [],
    "3October": [],
    "4October": [],
    "5October": [],
    "6October": [],
    "7October": [],
    "8October": [],
    "9October": [],
    "10October": [
        {
            "title": "The Orange Box released",
            "year": 2007,
            "youtube": false,
            "image": "https://upload.wikimedia.org/wikipedia/en/2/23/Hltob-win-cover.jpg",
            "info": "On this day, Valve published a compilation of games, of which 3 were new releases: Half Life 2: Episode Two, Portal, and Team Fortress 2. Each of these franchises have their own assortments of popular memes, although some notable ones include \"Half Life 3 Confirmed\", \"The Cake is a Lie\", and Nope.avi.",
            "kym": "https://knowyourmeme.com/memes/subcultures/valve"
        }
    ],
    "11October": [],
    "12October": [],
    "13October": [],
    "14October": [],
    "15October": [],
    "16October": [],
    "17October": [],
    "18October": [],
    "19October": [],
    "20October": [],
    "21October": [],
    "22October": [],
    "23October": [],
    "24October": [],
    "25October": [],
    "26October": [],
    "27October": [],
    "28October": [],
    "29October": [],
    "30October": [],
    "31October": [],
    "1November": [],
    "2November": [],
    "3November": [],
    "4November": [],
    "5November": [],
    "6November": [],
    "7November": [],
    "8November": [],
    "9November": [],
    "10November": [],
    "11November": [],
    "12November": [],
    "13November": [],
    "14November": [],
    "15November": [],
    "16November": [],
    "17November": [],
    "18November": [],
    "19November": [],
    "20November": [],
    "21November": [],
    "22November": [],
    "23November": [],
    "24November": [],
    "25November": [],
    "26November": [],
    "27November": [
        {
            "title": "\"Bode\" created",
            "year": 2016,
            "youtube": false,
            "image": "https://i.kym-cdn.com/photos/images/newsfeed/001/195/668/4ac.png",
            "info": "On this day, Tumblr user loghains posted this. In it, they say that they dreamt of a new meme format, in which pictures of fat cats are captioned with \"bode\" (short for bodacious). Within a few days, other Tumblr users had started to create memes using this format, and it became a popular format on the site.",
            "kym": "https://knowyourmeme.com/memes/bode"
        }
    ],
    "28November": [],
    "29November": [],
    "30November": [],
    "1December": [],
    "2December": [],
    "3December": [],
    "4December": [],
    "5December": [],
    "6December": [],
    "7December": [],
    "8December": [],
    "9December": [],
    "10December": [],
    "11December": [],
    "12December": [],
    "13December": [],
    "14December": [],
    "15December": [],
    "16December": [],
    "17December": [],
    "18December": [],
    "19December": [],
    "20December": [],
    "21December": [],
    "22December": [],
    "23December": [],
    "24December": [],
    "25December": [],
    "26December": [],
    "27December": [],
    "28December": [],
    "29December": [],
    "30December": [],
    "31December": []
}